export const SUFFICIENT_BALANCE_FOR_CHROMIA_VOUCHER = 40;
export const SUFFICIENT_BALANCE_FOR_COMMUNITY_VOUCHER = 10;

export const CHROMIA_PLAN = "CHROMIA";
export const COMMUNITY_PLAN = "COMMUNITY";

export const BYTES_IN_MB = 1024 * 1024;