name: continuous-integration

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Build Filehub image
        run: ./build-image.sh
        working-directory: filehub

      - name: Build Filechain image
        run: ./build-image.sh
        working-directory: filechain

      - name: Start Postgres
        run: docker-compose up -d postgres
        working-directory: test

      - name: Start Filehub
        run: docker-compose up -d filehub
        working-directory: test

      - name: Sleep for 15 seconds
        uses: jakejarvis/wait-action@master
        with:
          time: '15s'

      - name: Output Filehubs logs to verify it started correctly
        run: docker logs filehub

      - name: Save Filehub BRID to .env
        run: ./env.sh
        working-directory: test

      - name: Start Filechains
        run: docker-compose up -d
        working-directory: test

      - name: Sleep for 15 seconds
        uses: jakejarvis/wait-action@master
        with:
          time: '15s'

      - name: Save Filechain BRIDs to .env
        run: ./add-filechain-to-env.sh
        working-directory: test

      - name: Output env
        run: cat .env
        working-directory: test

      # Build File Storage Client (fs-client)
      - name: Install dependencies for fs-client
        run: npm install
        working-directory: client
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      - name: Build fs-client
        run: npm run build
        working-directory: client
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

      # Run test client
      - name: Install dependencies
        run: npm install
        working-directory: test
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      - name: Run CHROMIA Filechain tests
        run: npm run test
        working-directory: test
        continue-on-error: false

      - name: Output Filehub log
        run: docker logs filehub

      - name: Output CHROMIA Filechain1 log
        run: docker logs filechain1

      - name: Output COMMUNITY Filechain2 log
        run: docker logs filechain2
