name: formatting

on:
  schedule:
    - cron: "10 23 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Install dependencies
        run: npm install
        working-directory: client

      - name: Format client code
        run: npm run format
        working-directory: client

      - name: Install dependencies
        run: npm install
        working-directory: test

      - name: Format test code
        run: npm run format
        working-directory: test

      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "Formatter"
          git commit -m "Format code" -a
        continue-on-error: true
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true