name: Publish NPM

on:
  push:
    tags:
      - client-v*

jobs:
  build:
    needs: continuous-integration
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Publish to npm
        run: npm publish --dry-run
        working-directory: client
        env: # More info about the environment variables in the README
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }} # You need to set this in your repo settings