name: publish-fs-client

on:
  push:
    tags:
      - client-v*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Build npm package
        run: npm run build
        working-directory: client

      - name: Publish to npm
        run: npm publish
        working-directory: client
        env: # More info about the environment variables in the README
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }} # You need to set this in your repo settings