name: publish-fs-client

on:
  push:
    tags:
      - client-v*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Install npm dependencies
        run: npm install
        working-directory: client
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

      - name: Build npm package
        run: npm run build
        working-directory: client

      - name: Publish to npm
        run: npm publish --access public
        working-directory: client
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}