name: push-filehub

on:
  push:
    tags:
      - filehub-v*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Build Filehub image
        run: ./build-image.sh
        working-directory: filehub

      - name: Extract tag name
        id: tag
        uses: actions/github-script@0.2.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            return context.payload.ref;

      - name: Filter tag prefix
        id: tag_version
        uses: frabert/replace-string-action@v1.1
        with:
          pattern: ".*-v"
          string: ${{ steps.tag.outputs.result }}
          replace-with: ""

      - name: Filter tag prefix
        id: tag_final
        uses: frabert/replace-string-action@v1.1
        with:
          pattern: "\""
          string: ${{ steps.tag_version.outputs.replaced }}
          replace-with: ""

      - name: Publish image
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: snieking/filehub
          tags: ${{ steps.tag_final.outputs.replaced }}
          username: snieking
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          workdir: filehub